
type Post {
  id: ID!
  title: String!
  description: String!
}

type Query {
  totalPost: Int!
  allPosts: [Post!]!
}

# Input type
input PostInput {
  title: String!
  description: String!
}

# Mutations
type Mutation {
  newPost(input: PostInput!): Post!
}